name: store_app2
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  cloud_firestore: ^6.0.0
  country_state_city_picker: ^1.2.8
  dio: ^5.9.0
  equatable: ^2.0.7
  firebase_auth: ^6.0.0
  firebase_core: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_facebook_auth: ^6.0.0
  flutter_google_places_hoc081098: ^2.0.0
  flutter_stripe: ^12.1.1
  font_awesome_flutter: ^10.9.0
  google_places_flutter: ^2.1.1
  google_sign_in: ^6.2.1
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
